### ISSUE TITLE
Always uses original image size.

### ISSUE THREAD

**Issue by EnigmaWeb** [EnigmaWeb/wp-catalogue#12]
https://wordpress.org/support/topic/good-but-not-for-permanent-use

He's right... WPC appears to always use the full size original image. I feel like this could explain a lot of why our resize options have never worked very well... it doesn't matter what they're doing if we always call the original instead of the resized version.  Could you look into this?

**Comment by EnigmaWeb** [comment]
This fix has been applied in Pro version... please can it also be applied to free now?

**Comment by Base29** [comment]
Some users are experiencing issues with the new functionality that we have applied so I haven’t implemented on the free version yet … I will implement it as soon as it is perfect for the pro version

**Comment by Base29** [comment]
Adding the new resizing functionality to the free version ...

**Comment by Base29** [comment]
Fixed in 1.7.5
