### ISSUE TITLE
Problems with Uninstall

### ISSUE THREAD

**Issue by EnigmaWeb** [EnigmaWeb/wp-catalogue#16]
Per https://wordpress.org/support/topic/problems-with-uninstall

> You have an error in your uninstall script that is causing your plugin to delete taxonomy terms that are not related to your plugin.
> 
> It's this line:
> `$delete1 = $wpdb->query("DELETE FROM wp_terms WHERE term_id='$tax_id'");`
> 
> `$tax_id` is actually term_taxonomy_id per your previous query, which is NOT the same as term_id. this is causing records to be deleted from the wp_terms table that shouldn't be, and affecting other plugins.

**Comment by EnigmaWeb** [comment]
Fairly serious, should update ASAP

**Comment by Base29** [comment]
On it …

**Comment by Base29** [comment]
Fixed in version 1.7.6

**Comment by EnigmaWeb** [comment]
Nice work. Thanks
